# Copyright (C) 2018-2022 Heinrich-Heine-Universitaet Duesseldorf,
# Institute of Computer Science, Department Operating Systems
# Burak Akguel, Christian Gesse, Fabian Ruhland, Filip Krakowski, Michael Schoettner
#
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

language: cpp
compiler: gcc
os: linux
dist: bionic

jobs:
  include:
    - name: build
      addons:
        apt:
          packages:
            - cmake
            - make
            - nasm
            - gcc-multilib
            - g++-multilib
            - mtools
            - dosfstools
      before_script:
        - wget -O rocket https://github.com/krakowski/rocket/releases/download/${ROCKET_VERSION}/rocket-${ROCKET_VERSION}-linux-amd64
        - chmod +x rocket
      script:
        - ./build.sh

      deploy:
        provider: releases
        token: ${API_KEY}
        cleanup: false
        file:
          - hhuOS.img
          - hhuOS.bin
        on:
          repo: hhuOS/hhuOS
          branch: master
          tags: true