language: cpp
compiler: gcc
os: linux
dist: bionic

jobs:
  include:
    - name: build
      addons:
        apt:
          packages:
            - cmake
            - make
            - nasm
            - gcc-multilib
            - g++-multilib
            - mtools
      before_script:
        - wget -O rocket https://github.com/krakowski/rocket/releases/download/${ROCKET_VERSION}/rocket-${ROCKET_VERSION}-linux-amd64
        - chmod +x rocket
      script:
        - ./build.sh

      deploy:
        provider: releases
        token: ${API_KEY}
        cleanup: false
        file:
          - hhuOS.img
        on:
          repo: hhuOS/hhuOS
          branch: master
          tags: true