sudo: required

services:
  - docker
  
env:
  global:
    - DOCKER_REPOSITORY=hhuos/builder
    - DOCKER_TAG=1.0
    - CONTAINER_NAME=builder
    - CLONE_URL=git@github.com:hhuOS/hhuOS.git
    - HHUOS_DIR=hhuOS/src/os

before_install:
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile

install:
  - docker build -t ${DOCKER_REPOSITORY}:${DOCKER_TAG} .
  - docker run --name ${CONTAINER_NAME} --rm -i -t ${DOCKER_REPOSITORY}:${DOCKER_TAG} bash

script:
  - docker exec -d ${CONTAINER_NAME} git clone ${CLONE_URL}
  - docker exec -d ${CONTAINER_NAME} cd ${HHUOS_DIR}
  - docker exec -d ${CONTAINER_NAME} make -j4 iso

notifications:
  slack:
    secure: IWFNiPHHK8QEFO7B+WRmD5FUUHWISvp22pX/r/b4z4pRw/dGOBRJR819stRIWCKbz7rjBtz76O1/cwagXMSpmWyD9rxu/HBqKRdxLp00OT48b68d8o/+G+yx1oDXtl2SGphOjcCm+ld7/D2heJiHri2v4eoFLV8C2D19vFhJ29DifpN/IEggVAY/DmvSN80C+wIGXa6763vW3mxQthIvc3CCcf/yyhd5U2J29+UZOavR81y9T7DQyN7/cDHRcEM1XDT87IJ98zhwdHNDLk0a9omosqTFsYWTg6NZxfeGG6shY4r0qVjQBkjnqT30B+S4JD5ICZh7tdfkgfFJh2lsUf9AwIBJvT/3nfRXVm3nIuGX4p5gCD9T8vgtU8pxRRnN9qsNwaS38kzstg17sjBX0yK1oxB+rNZrIT8bJuMn1gcVbeNuEltciYKswaFCkPxtiWWwBgFW7cel153WMPSBo7SGUneQ+FE2KMLSPvauKOD64qw+KleAIXNyaXJtsoGtXfERqSm9jDIihwmvinrQvKwU4yZzlS2wy44/ntbOwnR03zCYnNkH7gOaUYmNY5JBpZP01XPFDxBvs+rgYRFSLJmZnrFayZ4RHO4d2xwvywOxocGCKUtlkpzJZ9EEY6Ov4+sypqoFN6zrH8wjn54FjDcZdnuIvhbTUnU+wQ0RouI=
