default = "hhuOS"
timeout = 0
log_level = "info"

[entries]
  [entries.hhuOS]
    name = "hhuOS"
    image = "\\hhuOS.bin"
    modules = [ { image = "\\hhuOS.initrd", argv = "initrd" } ]
    argv = ""
