default = "hhuOS"
timeout = 0
log_level = "debug"

[entries]
  [entries.hhuOS]
    name = "hhuOS"
    image = "\\hhuOS.bin"
    modules = [ { image = "\\hhuOS.initrd", argv = "initrd" } ]
    quirks = [ "ModulesBelow200Mb" ]
